session: ide
root: ~
attach: true

# Define reusable window configuration
window_template: &devenv
  layout: main-vertical
  commands:
    - nvim -c NvimTreeToggle
  panes:
    - commands: []
      size: "25%"

windows:
  - name: nixos
    root: ~/nixos
    <<: *devenv
  - name: dotfiles
    root: ~/dotfiles
    <<: *devenv
  - name: dotfiles/home-manager
    root: ~/dotfiles/home-manager
    <<: *devenv
  - name: dotfiles/home-manager/ide/nixvim/bat.nvim
    root: ~/dotfiles/home-manager/ide/nixvim/bat.nvim
    <<: *devenv
  - name: dotfiles/cuda
    root: ~/dotfiles/cuda
    <<: *devenv
  - name: symmetry
    root: ~/symmetry
    <<: *devenv
  - name: json
    root: ~/json
    <<: *devenv
  - name: challenges
    root: ~/challenges
    <<: *devenv
